package:
  name: cached-property
  version: "1.3.0"

source:
  fn: cached-property-1.3.0.tar.gz
  url: https://pypi.python.org/packages/source/c/cached-property/cached-property-1.3.0.tar.gz
  md5: 4a6039f7418007275505e355359396a8

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://github.com/pydanny/cached-property
  license: BSD License
  summary: 'A decorator for caching properties in classes.'
